### ISSUE TITLE
endpoints: overlapping with specialized vocabulary

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/invenio-vocabularies#10]
Sincd the specialized vocabularies define their own ES mappings they don't share the same index as the generic vocabulary. Therefore we have to manually register a new endpoint on `/vocabulary/[our_specialized_vocabulary]` for each specialized vocabulary type. However this doesn't work because the endpoint `/vocabulary` is already registered by the generic vocabulary - and it will fall back to that one, which will return an empty result because the vocabulary is not on this index.

For the subjects vocabulary, the current endpoint was set to `/subjects` instead of `/vocabularies/subjects` as a workaround to this limitation.

A solution might be to avoid matching the URL if the vocabulary type is not recognized, that way it will always fall back to the correct serializer.

See inveniosoftware/invenio-rdm-records#312

**Comment by ppanero** [comment]
Not applicable anymore. Custom vocabularies like affiliations and subjects have their own endpoint which is not prefixed by `/vocabularies`
