### ISSUE TITLE
schemas: move "VocabularySchema" to invenio-vocabularies

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-vocabularies#188]
schema `VocabularySchema` is currently defined in `invenio-rdm-records`, making it impossible to re-use in some modules thus creating duplicated schema declaration. See: https://github.com/inveniosoftware/invenio-communities/pull/531#discussion_r862812839

invenio-rdm-records: https://github.com/inveniosoftware/invenio-rdm-records/blob/3b24e3097472adaf763480f907ea93ff8e831051/invenio_rdm_records/services/schemas/metadata.py#L184-L187

**Comment by ppanero** [comment]
We need to address this since we also need it for the schema of vocabularies as custom values. Note that contrib also have very similar "Relations" schema (e.g. AffiliationsRelationSchema and FundersRelationSchema)

**Comment by ppanero** [comment]
in the process move the `VocabularyCF` from rec-resources to invenio-vocabularies so it can profit from said schema

**Comment by ppanero** [comment]
closed in favour of https://github.com/inveniosoftware/invenio-vocabularies/issues/205
