### ISSUE TITLE
ROR affiliations/funders update

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-vocabularies#305]
- Make sure the datastreams workflow works (new and updated entries)

**Comment by ptamarit** [comment]
# Funders

* `convert`
    * The command works:
    `$ invenio vocabularies convert -v funders -o v1.46-2024-05-02-ror-data.zip -t funders.yaml`
    * Data comparison
        * The default file only has 21 entries; a [blog post explaining the addition of extra funders](https://blog.zenodo.org/2017/10/10/grants-and-language-update/) indicated that it is manually curated.
        * From the data dump, we get extra identifiers: `isni`, `doi`, `grid`
        * The `country` appears before the `id`; order other than alphabetical can be achieved by setting `sort_keys=False` in `yaml.safe_dump`
        * 2 tabs indented instead of 4 tabs indented; did not manage to change this, but it could be done with Prettier.
        * Some names changed (e.g. `05k73zm37` is now `Research Council of Finland` instead of `Academy of Finland`, https://ror.org/05k73zm37 shows the "old" name as an alias, but we don't use them in the funders transformation)
        * We now include `title` in other languages than `en` (e.g. `fi: Suomen Akatemia` and `sv: Finlands Akademi` for https://ror.org/05k73zm37)
* `import`
    * The command works:
    `invenio vocabularies import -v funders -o ../v1.46-2024-05-02-ror-data.zip`
    * It does take a very long time to run (more than 30 minutes)
    * It shows warnings about existing entries and continues to proceed with next entries:
        ```
        FundersServiceWriter: ["Vocabulary entry already exists: {'id': '000000000', 'name': 'Name', 'country': 'CH', 'title': {'en': 'Name'}, 'identifiers': [{'identifier': '000000000', 'scheme': 'ror'}, {'identifier': '0000 0000 0000 0000', 'scheme': 'isni'}, {'identifier': '10.13039/000000000000', 'scheme': 'doi'}, {'identifier': 'grid.00000.00', 'scheme': 'grid'}]}"]
        ```
        * Using the `update` command instead of the `import` command should update existing entries instead of showing warnings (did not test it yet)

**Comment by ptamarit** [comment]
Closing for now since the ROR datastreams funders update works with the fix for the 2 JSON files linked to this issue.
Other tasks like migrating affiliations to use datastreams, or upgrading to ROR v2 format, will be done as separated tasks.
