### ISSUE TITLE
New API endpoint which returns a list of all vocabularies

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-vocabularies#306]
- create a new blueprint `/api/vocabularies` that returns a list of all vocabularies
  - see https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/resources/resource.py#L57

**Comment by karkraeg** [comment]
I just reused https://docs.narodni-repozitar.cz/api/vocabularies/ as an example for the API.

**Comment by karkraeg** [comment]
will be closed with https://github.com/inveniosoftware/invenio-vocabularies/pull/310/files
