### ISSUE TITLE
Admin panel to list all vocabularies

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-vocabularies#307]
![](https://codimd.web.cern.ch/uploads/upload_b20e312a8034c9bd307e5cb0184e1e26.png)

**Comment by karkraeg** [comment]
We implemented a working Admin panel in https://github.com/ulbmuenster/invenio-vocabularies/tree/all_vocabularies_endpoint

![image](https://github.com/inveniosoftware/invenio-vocabularies/assets/8436596/03050e1b-9be5-4e47-a7e7-1227814a6988)

The API is yet to be defined and also we are not sure why one would need the `System` badge?

**Comment by karkraeg** [comment]
missing: 

- `System` Badge
- optional Delete Button

**Comment by karkraeg** [comment]
@slint is it true that we have three types of vocabularies?

- system "custom" vocabularies (names, affiliations, awards, funders) (system badge)
- system "generic" vocabularies (licenses, languages...) (no badge)
- user defined new vocabularies (in the screenshot `code:developmentStatus`) - are deleteable
