### ISSUE TITLE
ORCID AWS Public Data Sync

### ISSUE THREAD

**Issue by ptamarit** [inveniosoftware/invenio-vocabularies#314]
Secrets stored on `tbag` under:
* `ORCID_AWS_ACCESS_KEY`
* `ORCID_AWS_SECRET_ACCESS_KEY`

Validation of the access:
* Install the AWS CLI (step 2 in [Get started with the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-using-examples))
* Log in
    ```bash
    aws configure
    AWS Access Key ID [None]: <ORCID_AWS_ACCESS_KEY>
    AWS Secret Access Key [None]: <ORCID_AWS_SECRET_ACCESS_KEY>
    Default region name [None]: 
    Default output format [None]: 
    ```
* List content of the buckets:
    ```bash
    aws s3 ls s3://v3.0-summaries
    aws s3 ls s3://v3.0-activities-a
    aws s3 ls s3://v3.0-activities-b
    aws s3 ls s3://v3.0-activities-c
    aws s3 ls s3://orcid-lambda-file
    ```
* Log out
    ```bash
    aws configure
    AWS Access Key ID [None]: dummy
    AWS Secret Access Key [None]: dummy
    Default region name [None]: 
    Default output format [None]: 
    ```

**Comment by tmorrell** [comment]
Just an FYI - the python dependencies for awscli can be a real pain. For compatibility with https://github.com/inveniosoftware/invenio-s3 you might want to use s3fs https://s3fs.readthedocs.io/en/latest/

**Comment by ptamarit** [comment]
Closing this issue since the implementation was done in #353.
