### ISSUE TITLE
Switch affiliations to datastream

### ISSUE THREAD

**Issue by tmorrell** [inveniosoftware/invenio-vocabularies#318]
Switch affiliations vocabulary to datastream and make it consistent with funders. This also needs to move the ROR transformer to common and label it more generally.

**Comment by tmorrell** [comment]
Main PR is https://github.com/inveniosoftware/invenio-vocabularies/pull/327 and small one to make it work in RDM https://github.com/inveniosoftware/invenio-app-rdm/pull/2680

**Comment by tmorrell** [comment]
Additionally there are small documentation https://github.com/inveniosoftware/docs-invenio-rdm/pull/639, cookiecutter https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/282, and rdm-records PRs https://github.com/inveniosoftware/invenio-rdm-records/pull/1752 that should be looked at once the main PR is merged.

**Comment by tmorrell** [comment]
Will reopen until there is a vocabularies release and we can merge the app-rdm pr.

**Comment by slint** [comment]
Didn't mean to close the issue, but merging connected PRs does this automatically 😅. 

We're planning to merge everything next week, but need to orchestrate releases as well, to make sure dependencies don't break.

**Comment by tmorrell** [comment]
Yup, I'll let you all handle that release dance!
