### ISSUE TITLE
Improve ORCiD transformation

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-vocabularies#369]
- [x] Filter out any entries that have `given_name` or `family_name` matching the characters `_!.+*&^%@~[]{}` or digits, or emojis
- [ ] Make sure that affiliations are parsed correctly and that we include ROR IDs if present

**Comment by yashlamba** [comment]
Partly done by #376

**Comment by ptamarit** [comment]
Discussed at the standup: this is done.
