### ISSUE TITLE
Integrate EuroSci Vocabulary

### ISSUE THREAD

**Issue by 0einstein0** [inveniosoftware/invenio-vocabularies#381]
- Update euroscivoc to include hierarchy information
- Update ids to use notation instead of uri
- Store uri as separate identifiers

Download from here: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/euroscivoc

**Comment by alejandromumo** [comment]
If the PR addresses both issues (https://github.com/zenodo/zenodo-rdm/issues/986), I'd just close this one and move the description to the other one.

**Comment by 0einstein0** [comment]
Closed in favour of https://github.com/zenodo/zenodo-rdm/issues/986
