### ISSUE TITLE
Implement read_many

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-vocabularies#43]
When serializing to datacite, having a read_many to retrieve multiple subjects (vocabularies) at once would be great.

**Comment by ppanero** [comment]
read many is available since invenio-vocabularies uses invenio-records-resources

**Comment by fenekku** [comment]
@ppanero that's exactly what I mean. `read_many` is different for vocabularies because the ids are actually `('<type>', <id>)` . So a vocabulary-specific `read_many` is needed.
