### ISSUE TITLE
Improve search performance

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/invenio-vocabularies#5]
The vocabulary type name resolution has a significant impact on performance, particularly when listing records.

What happens is that the functions `dump`/`load` (in `dumper_extensions.py`) are called for each search result item. The vocabulary type resolution therefore happens for each of them; and that seems to be the bottleneck.

**Comment by ppanero** [comment]
@lnielsen this should be fixed with the new implementation no?

**Comment by ppanero** [comment]
ping @lnielsen I see no reference to any dumper farther from the one for [relations](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/records/api.py#L72). Is this still an issue?
