### ISSUE TITLE
Split Subjects into its own Vocabulary

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-vocabularies#63]
Review list of steps to do like affiliations but for subjects:

**Data layer**

- [x] Define relation in CommonFIeldsMixin.
    - [x] Determine which fields to dump in ES index.
- [x] JSONShema: Do not modify an already released schema, create new version instead.
- [x] JSONSchema: Define or review existing property
    - List or single?
    - Mixed linked with non-linked?
- [x] Mappings adapt to JSONSchema and dumped fields.

**Service layer**

- [x] Schema: Fix metadata schema.
- [x] Facets: Do we need facets? Guillaume: let's skip for now

**Presentation layer**

- [x] Fix REST API serializations
- [x] Fix other serialization formats.

**Tests**

- [x] Add tests that record linking is wokring as expected (e.g. from service layer).
    - Bad and good data.
- [x] Add REST API tests for serialization, facets
- [x] Ensure that I18N is tested properly if required.

Follow structure from:

https://codimd.web.cern.ch/vc6wJipAS66l1XjwKjYdmA?both#

**Comment by ppanero** [comment]
>  Ensure that I18N is tested properly if required.

No i18n
