### ISSUE TITLE
models: remove VocabularySubtype

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-vocabularies#69]
Remove [VocabularySubtype](https://github.com/inveniosoftware/invenio-vocabularies/blob/master/invenio_vocabularies/records/models.py#L58) as it should not exists. Instead subjects vocabulary should have a SubjectScheme model that similar to this subtype.

**Comment by fenekku** [comment]
Closed via https://github.com/inveniosoftware/invenio-vocabularies/pull/67 .(SubjectsScheme is VocabularyScheme)
