### ISSUE TITLE
Vocabulary reference class implementation should be moved from rdm-records

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-vocabularies#98]
Vocabularies have full Marshmallow schemas. However, when used *nested* e.g. [from rdm-records](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/schemas/metadata.py#L65) a simple schema is used. Normally only containing `id` and another attribute for custom cases.

Those schemas are defined in RDM-Records:
- [AffiliationSchema](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/schemas/metadata.py#L65)
- [SubjectSchema](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/schemas/metadata.py#L88)
- Generic [VocabularySchema](https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/services/schemas/metadata.py#L182)
- Maybe some others

With the `names` vocabulary implementation, the `AffiliationSchema` had to be copy pasted to this module. Should those schemas live in invenio-vocabularies?

**Comment by slint** [comment]
I think is somewhat addressed by https://github.com/inveniosoftware/invenio-vocabularies/pull/102. To be reviewed at some point.

**Comment by ppanero** [comment]
Just checked... Yes it is, but we need to use the new ones. It's an easy fix, I can take care of it this week (re-opening...)
